/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiCvRouteImport } from './routes/api/cv'
import { Route as AppJobSearchRouteImport } from './routes/_app/job-search'
import { Route as AppCvBuilderRouteImport } from './routes/_app/cv-builder'
import { Route as ApiInternalDebugDbSchemaRouteImport } from './routes/api/internal/debug/db-schema'
import { Route as ApiCvCvProfileIdVersionsRouteImport } from './routes/api/cv/$cvProfileId/versions'
import { Route as ApiCvCvProfileIdVersionVersionIdRouteImport } from './routes/api/cv/$cvProfileId/version/$versionId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCvRoute = ApiCvRouteImport.update({
  id: '/api/cv',
  path: '/api/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJobSearchRoute = AppJobSearchRouteImport.update({
  id: '/job-search',
  path: '/job-search',
  getParentRoute: () => AppRoute,
} as any)
const AppCvBuilderRoute = AppCvBuilderRouteImport.update({
  id: '/cv-builder',
  path: '/cv-builder',
  getParentRoute: () => AppRoute,
} as any)
const ApiInternalDebugDbSchemaRoute =
  ApiInternalDebugDbSchemaRouteImport.update({
    id: '/api/internal/debug/db-schema',
    path: '/api/internal/debug/db-schema',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCvCvProfileIdVersionsRoute =
  ApiCvCvProfileIdVersionsRouteImport.update({
    id: '/$cvProfileId/versions',
    path: '/$cvProfileId/versions',
    getParentRoute: () => ApiCvRoute,
  } as any)
const ApiCvCvProfileIdVersionVersionIdRoute =
  ApiCvCvProfileIdVersionVersionIdRouteImport.update({
    id: '/$cvProfileId/version/$versionId',
    path: '/$cvProfileId/version/$versionId',
    getParentRoute: () => ApiCvRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cv-builder': typeof AppCvBuilderRoute
  '/job-search': typeof AppJobSearchRoute
  '/api/cv': typeof ApiCvRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/cv/$cvProfileId/versions': typeof ApiCvCvProfileIdVersionsRoute
  '/api/internal/debug/db-schema': typeof ApiInternalDebugDbSchemaRoute
  '/api/cv/$cvProfileId/version/$versionId': typeof ApiCvCvProfileIdVersionVersionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cv-builder': typeof AppCvBuilderRoute
  '/job-search': typeof AppJobSearchRoute
  '/api/cv': typeof ApiCvRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/cv/$cvProfileId/versions': typeof ApiCvCvProfileIdVersionsRoute
  '/api/internal/debug/db-schema': typeof ApiInternalDebugDbSchemaRoute
  '/api/cv/$cvProfileId/version/$versionId': typeof ApiCvCvProfileIdVersionVersionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/about': typeof AboutRoute
  '/_app/cv-builder': typeof AppCvBuilderRoute
  '/_app/job-search': typeof AppJobSearchRoute
  '/api/cv': typeof ApiCvRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/cv/$cvProfileId/versions': typeof ApiCvCvProfileIdVersionsRoute
  '/api/internal/debug/db-schema': typeof ApiInternalDebugDbSchemaRoute
  '/api/cv/$cvProfileId/version/$versionId': typeof ApiCvCvProfileIdVersionVersionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cv-builder'
    | '/job-search'
    | '/api/cv'
    | '/api/health'
    | '/api/cv/$cvProfileId/versions'
    | '/api/internal/debug/db-schema'
    | '/api/cv/$cvProfileId/version/$versionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cv-builder'
    | '/job-search'
    | '/api/cv'
    | '/api/health'
    | '/api/cv/$cvProfileId/versions'
    | '/api/internal/debug/db-schema'
    | '/api/cv/$cvProfileId/version/$versionId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/about'
    | '/_app/cv-builder'
    | '/_app/job-search'
    | '/api/cv'
    | '/api/health'
    | '/api/cv/$cvProfileId/versions'
    | '/api/internal/debug/db-schema'
    | '/api/cv/$cvProfileId/version/$versionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AboutRoute: typeof AboutRoute
  ApiCvRoute: typeof ApiCvRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInternalDebugDbSchemaRoute: typeof ApiInternalDebugDbSchemaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cv': {
      id: '/api/cv'
      path: '/api/cv'
      fullPath: '/api/cv'
      preLoaderRoute: typeof ApiCvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/job-search': {
      id: '/_app/job-search'
      path: '/job-search'
      fullPath: '/job-search'
      preLoaderRoute: typeof AppJobSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cv-builder': {
      id: '/_app/cv-builder'
      path: '/cv-builder'
      fullPath: '/cv-builder'
      preLoaderRoute: typeof AppCvBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/internal/debug/db-schema': {
      id: '/api/internal/debug/db-schema'
      path: '/api/internal/debug/db-schema'
      fullPath: '/api/internal/debug/db-schema'
      preLoaderRoute: typeof ApiInternalDebugDbSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cv/$cvProfileId/versions': {
      id: '/api/cv/$cvProfileId/versions'
      path: '/$cvProfileId/versions'
      fullPath: '/api/cv/$cvProfileId/versions'
      preLoaderRoute: typeof ApiCvCvProfileIdVersionsRouteImport
      parentRoute: typeof ApiCvRoute
    }
    '/api/cv/$cvProfileId/version/$versionId': {
      id: '/api/cv/$cvProfileId/version/$versionId'
      path: '/$cvProfileId/version/$versionId'
      fullPath: '/api/cv/$cvProfileId/version/$versionId'
      preLoaderRoute: typeof ApiCvCvProfileIdVersionVersionIdRouteImport
      parentRoute: typeof ApiCvRoute
    }
  }
}

interface AppRouteChildren {
  AppCvBuilderRoute: typeof AppCvBuilderRoute
  AppJobSearchRoute: typeof AppJobSearchRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCvBuilderRoute: AppCvBuilderRoute,
  AppJobSearchRoute: AppJobSearchRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiCvRouteChildren {
  ApiCvCvProfileIdVersionsRoute: typeof ApiCvCvProfileIdVersionsRoute
  ApiCvCvProfileIdVersionVersionIdRoute: typeof ApiCvCvProfileIdVersionVersionIdRoute
}

const ApiCvRouteChildren: ApiCvRouteChildren = {
  ApiCvCvProfileIdVersionsRoute: ApiCvCvProfileIdVersionsRoute,
  ApiCvCvProfileIdVersionVersionIdRoute: ApiCvCvProfileIdVersionVersionIdRoute,
}

const ApiCvRouteWithChildren = ApiCvRoute._addFileChildren(ApiCvRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AboutRoute: AboutRoute,
  ApiCvRoute: ApiCvRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiInternalDebugDbSchemaRoute: ApiInternalDebugDbSchemaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
